### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by KhiemDuyNguyen** [Dean151/Go-game#3]
Hi, sorry for bother you.

Like title said, how to compile this java source code on Linux. Sorry I'm pretty new to java.

**Comment by Dean151** [comment]
Good question ^^'
This was a student project from 5-6 years ago.
At the time, I used an IDE to compile, like IntelliJ Idea ; or Eclipse.
Install an IDE, along with Java Runtime Developper.
You should then open the project with this IDE, and press play.
Sorry, I do not now much more ; and don't have time to dig deeper.

**Comment by KhiemDuyNguyen** [comment]
It's alright. Thank you for the answer. I compiled it by the terminal so it requires current folder to be in exact spot in order to work. 
It was for school project as well, but for an AI class, I just don't want to create a new game from scratch just to implement the AI part. Again, thank you for you answer.

**Comment by Dean151** [comment]
Damn, cool ^^
Hope this game will give you enough structure to work on you IA.
Good luck!
